services:
  postgres:
    image: postgres:16-alpine
    container_name: amethyst-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: amethyst
    ports:
      - "5432:5432"
    volumes:
      - amethyst_pg_data:/var/lib/postgresql/data

volumes:
  amethyst_pg_data:
