// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD12AHZW9rRy24GZV6GR8vAKSOe4I2IkWg',
    appId: '1:131297170179:web:999be99f88b7fd6ebd8f36',
    messagingSenderId: '131297170179',
    projectId: 'amethyst-3328a',
    authDomain: 'amethyst-3328a.firebaseapp.com',
    storageBucket: 'amethyst-3328a.firebasestorage.app',
    measurementId: 'G-3K6V51Q5RG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh4WmkSFuyI7EqX8XPbUbSdgAKTtfYuRE',
    appId: '1:131297170179:android:dba1e8d35aecc20abd8f36',
    messagingSenderId: '131297170179',
    projectId: 'amethyst-3328a',
    storageBucket: 'amethyst-3328a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6GMpEjfyyc5U2b72Jp0DpaY8LVc4xkDw',
    appId: '1:131297170179:ios:57642811672da183bd8f36',
    messagingSenderId: '131297170179',
    projectId: 'amethyst-3328a',
    storageBucket: 'amethyst-3328a.firebasestorage.app',
    iosBundleId: 'com.example.amethyst',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6GMpEjfyyc5U2b72Jp0DpaY8LVc4xkDw',
    appId: '1:131297170179:ios:57642811672da183bd8f36',
    messagingSenderId: '131297170179',
    projectId: 'amethyst-3328a',
    storageBucket: 'amethyst-3328a.firebasestorage.app',
    iosBundleId: 'com.example.amethyst',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD12AHZW9rRy24GZV6GR8vAKSOe4I2IkWg',
    appId: '1:131297170179:web:f4556734b41aa905bd8f36',
    messagingSenderId: '131297170179',
    projectId: 'amethyst-3328a',
    authDomain: 'amethyst-3328a.firebaseapp.com',
    storageBucket: 'amethyst-3328a.firebasestorage.app',
    measurementId: 'G-TX68973CLZ',
  );
}
